#!/bin/bash

#
# The following section shows the possible configuration options for the default 
# karaf scripts
#
# export JAVA_MIN_MEM # Minimum memory for the JVM
# export JAVA_MAX_MEM # Maximum memory for the JVM
# export JAVA_PERM_MEM # Minimum perm memory for the JVM
# export JAVA_MAX_PERM_MEM # Maximum perm memory for the JVM

# PDI Daemon configuration properties
# DAEMON_DEBUG # Enables debug mode
# KARAF_DEBUG_PORT
# SPARK_HOME="${HOME}/spark-2.1.0-bin-hadoop2.7/" # Location of Apache Spark Client distribution
# SPARK_APP="${HOME}/pdi-ee-client-7.1.0.0-12/data-integration" # Spark Karaf Assembly
# SPARK_MASTER="local"
# SPARK_DEPLOY_MODE="client"
# SPARK_DRIVER_JAVA_OPTS
# SPARK_EXECUTOR_JAVA_OPTS
# SPARK_DRIVER_MEMORY=4g # The amount of memory to allocate to the spark driver (1g, 2g, 8g, ...)
# SPARK_EXECUTOR_MEMORY=1g # The amount of memory to allocate to the spark executor (1g, 2g, 8g, ...)
# SPARK_DRIVER_DEBUG_PORT=5006
# SPARK_EXECUTOR_DEBUG_PORT=5007
# ASSEMBLY_ZIP # Spark Assembly Zip, this can be an HDFS reference
# SUSPEND_DEBUG
# HADOOP_CONF_DIR="${HOME}/yarn-conf" # Location where *-site.xml files reside for Hadoop Configuration
# HADOOP_USER="devuser"
# KEYTAB_NAME="devuser.keytab"
# KERBEROS_PRINCIPAL="devuser"
# DISABLE_PROXY_USER=false

# Embedded Zookeeper configuration properties
# ZOOKEEPER_CLIENT_PORT=2181  # Port to listen on for client connections
# ZOOKEEPER_TICK_TIME=2000
# ZOOKEEPER_INIT_LIMIT=10
# ZOOKEEPER_SYNC_LIMIT=5
# ZOOKEEPER_DATA_DIR=zkdata

# Zookeeper client configuration properties
# ZOOKEEPER_HOST=localhost    # Zookeeper server location
# ZOOKEEPER_PORT=2181         # Client port of the Zookeeper server
# ZOOKEEPER_TIMEOUT=3000      # Session timeout in ms

# Path to jaas configuration for Kerberos authentication
# JAAS_CFG
# KEYTAB_PATH